@startuml

entity Member {
    id
    --
    first_name
    last_name
    email

    project_id
}

entity Project {
    id
    --
    name
    projectstatus_id

    member_id
}

entity ProjectStatus {
    id
    --
    name
}


Project |o--o{ Member
ProjectStatus ||--o{ Project


@enduml